"""
Script generator.
Orchestrates a conversation between Claude (Anthropic) and ChatGPT (OpenAI)
to produce a full podcast episode script.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from anthropic import Anthropic
from openai import OpenAI

import config

logger = logging.getLogger(__name__)


def _load_prompt(name: str) -> str:
    """Load a prompt template from the prompts directory."""
    path = config.PROMPTS_DIR / name
    return path.read_text(encoding="utf-8")


def _build_episode_prompt(topics: list[dict], date: str) -> str:
    """Fill in the episode format template with today's topics."""
    template = _load_prompt("episode_format.txt")
    word_count = config.EPISODE_DURATION_MINUTES * 150  # ~150 words/min spoken

    topics_text = "\n".join(
        f"- [{t.get('category', 'main').upper()}] {t['title']}: {t['summary']}"
        + (f" (Angle: {t['angle']})" if t.get("angle") else "")
        for t in topics
    )

    return template.format(
        date=date,
        topics=topics_text,
        duration=config.EPISODE_DURATION_MINUTES,
        word_count=word_count,
    )


def generate_script(topics: list[dict]) -> dict:
    """
    Generate the full episode script.

    Strategy:
    1. Use Claude to draft the full script structure (it's good at nuance and format)
    2. Then run a "rewrite pass" where each host's lines are regenerated by their
       actual model, ensuring authentic voice.

    Returns the complete script as a dict with title, description, and segments.
    """
    date_str = datetime.now().strftime("%B %d, %Y")
    episode_prompt = _build_episode_prompt(topics, date_str)

    logger.info("Step 1: Generating initial script structure...")
    raw_script = _generate_initial_script(episode_prompt)

    logger.info("Step 2: Rewriting each host's lines through their own model...")
    final_script = _rewrite_with_authentic_voices(raw_script, topics, date_str)

    return final_script


def _generate_initial_script(episode_prompt: str) -> dict:
    """Use Claude to generate the initial script structure."""
    client = Anthropic(api_key=config.ANTHROPIC_API_KEY)

    response = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=8000,
        messages=[
            {
                "role": "user",
                "content": episode_prompt,
            }
        ],
        system=(
            "You are a podcast script writer. Generate a complete podcast script "
            "in the exact JSON format specified. Make it feel natural and conversational. "
            "Both hosts should have distinct personalities. Return ONLY valid JSON."
        ),
    )

    text = response.content[0].text

    # Extract JSON from the response (handle markdown code blocks)
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    try:
        return json.loads(text.strip())
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse initial script: {e}")
        logger.debug(f"Raw response: {text[:500]}")
        raise


def _rewrite_with_authentic_voices(
    script: dict, topics: list[dict], date_str: str
) -> dict:
    """
    Pass each host's lines through their actual model for authentic voice.
    Claude's lines go through Anthropic, ChatGPT's through OpenAI.
    """
    claude_prompt = _load_prompt("claude_host.txt")
    chatgpt_prompt = _load_prompt("chatgpt_host.txt")

    anthropic_client = Anthropic(api_key=config.ANTHROPIC_API_KEY)
    openai_client = OpenAI(api_key=config.OPENAI_API_KEY)

    for segment in script.get("segments", []):
        dialogue = segment.get("dialogue", [])
        # Build conversation context for this segment
        context_lines = []

        for i, line in enumerate(dialogue):
            speaker = line["speaker"]
            original_text = line["text"]

            # Build context: what's been said so far in this segment
            context = "\n".join(
                f"{l['speaker']}: {l['text']}" for l in context_lines
            )

            if speaker == "Claude":
                rewritten = _rewrite_claude_line(
                    anthropic_client, claude_prompt, context, original_text, segment
                )
            else:
                rewritten = _rewrite_chatgpt_line(
                    openai_client, chatgpt_prompt, context, original_text, segment
                )

            line["text"] = rewritten
            context_lines.append({"speaker": speaker, "text": rewritten})

    return script


def _rewrite_claude_line(
    client: Anthropic, persona: str, context: str, original: str, segment: dict
) -> str:
    """Rewrite a Claude line through the Anthropic API."""
    segment_type = segment.get("type", "")
    topic = segment.get("topic", "")

    response = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=500,
        system=persona,
        messages=[
            {
                "role": "user",
                "content": (
                    f"You're in the '{segment_type}' segment of today's podcast"
                    + (f" discussing: {topic}" if topic else "")
                    + ".\n\n"
                    + (f"Conversation so far:\n{context}\n\n" if context else "")
                    + f"Your scripted line is: \"{original}\"\n\n"
                    "Rewrite this in your authentic voice. Keep the same meaning "
                    "and information, but make it sound like YOU — Claude — actually "
                    "talking. Keep it roughly the same length. Return ONLY the "
                    "rewritten line, no quotes or attribution."
                ),
            }
        ],
    )
    return response.content[0].text.strip()


def _rewrite_chatgpt_line(
    client: OpenAI, persona: str, context: str, original: str, segment: dict
) -> str:
    """Rewrite a ChatGPT line through the OpenAI API."""
    segment_type = segment.get("type", "")
    topic = segment.get("topic", "")

    response = client.chat.completions.create(
        model=config.CHATGPT_MODEL,
        max_tokens=500,
        messages=[
            {"role": "system", "content": persona},
            {
                "role": "user",
                "content": (
                    f"You're in the '{segment_type}' segment of today's podcast"
                    + (f" discussing: {topic}" if topic else "")
                    + ".\n\n"
                    + (f"Conversation so far:\n{context}\n\n" if context else "")
                    + f"Your scripted line is: \"{original}\"\n\n"
                    "Rewrite this in your authentic voice. Keep the same meaning "
                    "and information, but make it sound like YOU — ChatGPT — actually "
                    "talking. Keep it roughly the same length. Return ONLY the "
                    "rewritten line, no quotes or attribution."
                ),
            },
        ],
    )
    return response.choices[0].message.content.strip()


def save_script(script: dict, output_dir: Path) -> Path:
    """Save the script to a JSON file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "script.json"
    path.write_text(json.dumps(script, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(f"Script saved to {path}")
    return path
