"""
Script generator.
Orchestrates a conversation between AI hosts (and optional guests)
to produce a full podcast episode script.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from anthropic import Anthropic
from openai import OpenAI

import config
from pipeline.cost_tracker import tracker

logger = logging.getLogger(__name__)


def _load_prompt(name: str) -> str:
    """Load a prompt template from the prompts directory."""
    path = config.PROMPTS_DIR / name
    return path.read_text(encoding="utf-8")


def _build_episode_prompt(topics: list[dict], date: str, roster: list[str]) -> str:
    """Fill in the episode format template with today's topics and roster."""
    template = _load_prompt("episode_format.txt")
    duration = config.EPISODE_DURATION_MINUTES
    word_count = duration * 150  # ~150 words/min spoken
    min_word_count = int(word_count * 0.8)  # hard floor

    # Scale exchange counts based on target duration
    # These are calibrated so total output matches the word count target
    if duration >= 25:
        main_story_count = 3
        main_exchanges = 12       # deep dives, ~5-7 min each
        cold_open_exchanges = 3
        lightning_exchanges = 4
        signoff_exchanges = 4
    elif duration >= 15:
        main_story_count = 2
        main_exchanges = 8
        cold_open_exchanges = 2
        lightning_exchanges = 3
        signoff_exchanges = 3
    else:
        main_story_count = 2
        main_exchanges = 5
        cold_open_exchanges = 2
        lightning_exchanges = 2
        signoff_exchanges = 2

    # Build dynamic host description
    speaker_parts = []
    for name in roster:
        company = config.SPEAKERS[name]["company"]
        role = config.SPEAKERS[name]["role"]
        if role == "guest":
            speaker_parts.append(f"guest {name} ({company})")
        else:
            speaker_parts.append(f"{name} ({company})")

    if len(speaker_parts) == 2:
        hosts_description = f"hosted by {speaker_parts[0]} and {speaker_parts[1]}"
    else:
        hosts_description = (
            "hosted by "
            + ", ".join(speaker_parts[:-1])
            + f", and {speaker_parts[-1]}"
        )

    speaker_names = ", ".join(f'"{name}"' for name in roster)

    # Build optional guest segment text
    guests_in_roster = [n for n in roster if config.SPEAKERS[n]["role"] == "guest"]
    if guests_in_roster:
        guest_names = " and ".join(guests_in_roster)
        guest_segment = (
            f"3b. GUEST SPOTLIGHT — {guest_names} shares a unique perspective "
            f"on one main story. Hosts ask pointed questions. ({main_exchanges} exchanges)\n"
        )
    else:
        guest_segment = ""

    topics_text = "\n".join(
        f"- [{t.get('category', 'main').upper()}] {t['title']}: {t['summary']}"
        + (f" (Angle: {t['angle']})" if t.get("angle") else "")
        for t in topics
    )

    return template.format(
        date=date,
        topics=topics_text,
        duration=duration,
        word_count=word_count,
        min_word_count=min_word_count,
        hosts_description=hosts_description,
        speaker_names=speaker_names,
        guest_segment=guest_segment,
        main_story_count=main_story_count,
        main_exchanges=main_exchanges,
        cold_open_exchanges=cold_open_exchanges,
        lightning_exchanges=lightning_exchanges,
        signoff_exchanges=signoff_exchanges,
    )


def generate_script(topics: list[dict], roster: list[str] | None = None) -> dict:
    """
    Generate the full episode script.

    Strategy:
    1. Use Claude to draft the full script structure (it's good at nuance and format)
    2. Then run a "rewrite pass" where each speaker's lines are regenerated by their
       actual model, ensuring authentic voice.

    Returns the complete script as a dict with title, description, segments, and roster.
    """
    if roster is None:
        roster = config.get_episode_roster()

    date_str = datetime.now().strftime("%B %d, %Y")
    episode_prompt = _build_episode_prompt(topics, date_str, roster)

    logger.info("Step 1: Generating initial script structure...")
    raw_script = _generate_initial_script(episode_prompt, roster)

    logger.info("Step 2: Rewriting each host's lines through their own model...")
    final_script = _rewrite_with_authentic_voices(raw_script, topics, date_str, roster)

    logger.info("Step 3: Generating YouTube-optimized title...")
    final_script["youtube_title"] = _generate_youtube_title(final_script, topics)

    # Attach roster metadata for downstream consumers
    final_script["roster"] = roster

    return final_script


def _generate_initial_script(episode_prompt: str, roster: list[str]) -> dict:
    """Use Claude to generate the initial script structure."""
    client = Anthropic(api_key=config.ANTHROPIC_API_KEY)

    speaker_count = len(roster)
    system_msg = (
        "You are a podcast script writer. Generate a complete podcast script "
        "in the exact JSON format specified. Make it feel natural and conversational. "
        f"There are {speaker_count} speakers — each should have a distinct personality. "
        "Return ONLY valid JSON."
    )

    response = client.messages.create(
        model=config.CLAUDE_MODEL,
        max_tokens=16000,
        messages=[{"role": "user", "content": episode_prompt}],
        system=system_msg,
    )

    # Track usage
    tracker.record(
        step="initial_script",
        model=config.CLAUDE_MODEL,
        input_tokens=response.usage.input_tokens,
        output_tokens=response.usage.output_tokens,
        speaker="Claude",
    )

    text = response.content[0].text

    # Extract JSON from the response (handle markdown code blocks)
    if "```json" in text:
        text = text.split("```json")[1].split("```")[0]
    elif "```" in text:
        text = text.split("```")[1].split("```")[0]

    try:
        return json.loads(text.strip())
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse initial script: {e}")
        logger.debug(f"Raw response: {text[:500]}")
        raise


# ---------------------------------------------------------------------------
# API client factory
# ---------------------------------------------------------------------------

def _get_api_clients(roster: list[str]) -> dict:
    """
    Create API clients for each speaker in the roster.
    Skips speakers whose API keys are not configured.
    Returns {speaker_name: client_instance}.
    """
    clients = {}

    for speaker in roster:
        speaker_config = config.SPEAKERS[speaker]
        api_type = speaker_config["api_type"]

        try:
            if api_type == "anthropic" and config.ANTHROPIC_API_KEY:
                clients[speaker] = Anthropic(api_key=config.ANTHROPIC_API_KEY)
            elif api_type == "openai" and config.OPENAI_API_KEY:
                clients[speaker] = OpenAI(api_key=config.OPENAI_API_KEY)
            elif api_type == "google" and config.GOOGLE_AI_API_KEY:
                import google.generativeai as genai
                genai.configure(api_key=config.GOOGLE_AI_API_KEY)
                clients[speaker] = genai.GenerativeModel(speaker_config["model"])
            elif api_type == "xai" and config.XAI_API_KEY:
                clients[speaker] = OpenAI(
                    api_key=config.XAI_API_KEY,
                    base_url="https://api.x.ai/v1",
                )
            else:
                logger.warning(
                    f"No API key for {speaker} ({api_type}) — "
                    "will use initial script text for this speaker"
                )
        except Exception as e:
            logger.warning(f"Failed to create client for {speaker}: {e}")

    return clients


# ---------------------------------------------------------------------------
# Unified line rewriter
# ---------------------------------------------------------------------------

def _rewrite_line(
    client, speaker: str, persona: str, context: str, original: str, segment: dict
) -> str:
    """Rewrite a line through the speaker's own API for authentic voice."""
    speaker_config = config.SPEAKERS[speaker]
    api_type = speaker_config["api_type"]
    model = speaker_config["model"]
    segment_type = segment.get("type", "")
    topic = segment.get("topic", "")

    user_content = (
        f"You're in the '{segment_type}' segment of today's podcast"
        + (f" discussing: {topic}" if topic else "")
        + ".\n\n"
        + (f"Conversation so far:\n{context}\n\n" if context else "")
        + f'Your scripted line is: "{original}"\n\n'
        "Rewrite this in your authentic voice. Keep the same meaning "
        f"and information, but make it sound like YOU — {speaker} — actually "
        "talking. Keep it roughly the same length. Return ONLY the "
        "rewritten line, no quotes or attribution.\n\n"
        "IMPORTANT: Do NOT use filler phrases like 'honestly', 'if I'm being honest', "
        "'that's a great point', 'absolutely', 'let's dive in', 'at the end of the day', "
        "or 'it's worth noting'. Use varied, natural language."
    )

    if api_type == "anthropic":
        response = client.messages.create(
            model=model,
            max_tokens=500,
            system=persona,
            messages=[{"role": "user", "content": user_content}],
        )
        tracker.record(
            step="voice_rewrite", model=model, speaker=speaker,
            input_tokens=response.usage.input_tokens,
            output_tokens=response.usage.output_tokens,
        )
        return response.content[0].text.strip()

    elif api_type in ("openai", "xai"):
        response = client.chat.completions.create(
            model=model,
            max_tokens=500,
            messages=[
                {"role": "system", "content": persona},
                {"role": "user", "content": user_content},
            ],
        )
        usage = response.usage
        if usage:
            tracker.record(
                step="voice_rewrite", model=model, speaker=speaker,
                input_tokens=usage.prompt_tokens,
                output_tokens=usage.completion_tokens,
            )
        return response.choices[0].message.content.strip()

    elif api_type == "google":
        response = client.generate_content(f"{persona}\n\n{user_content}")
        # Gemini usage metadata
        meta = getattr(response, "usage_metadata", None)
        if meta:
            tracker.record(
                step="voice_rewrite", model=model, speaker=speaker,
                input_tokens=getattr(meta, "prompt_token_count", 0),
                output_tokens=getattr(meta, "candidates_token_count", 0),
            )
        return response.text.strip()

    return original  # fallback


def _rewrite_with_authentic_voices(
    script: dict, topics: list[dict], date_str: str, roster: list[str]
) -> dict:
    """
    Pass each speaker's lines through their actual model for authentic voice.
    Speakers without API keys keep their initial script text unchanged.
    """
    # Load persona prompts for all speakers in the roster
    personas = {}
    for speaker in roster:
        prompt_file = config.SPEAKERS[speaker]["persona_prompt"]
        try:
            personas[speaker] = _load_prompt(prompt_file)
        except FileNotFoundError:
            logger.warning(f"No persona prompt found for {speaker}: {prompt_file}")

    # Create API clients (skips speakers with missing keys)
    clients = _get_api_clients(roster)

    for segment in script.get("segments", []):
        dialogue = segment.get("dialogue", [])
        context_lines = []

        for line in dialogue:
            speaker = line["speaker"]
            original_text = line["text"]

            context = "\n".join(
                f"{l['speaker']}: {l['text']}" for l in context_lines
            )

            # Only rewrite if we have both a client and a persona for this speaker
            if speaker in clients and speaker in personas:
                try:
                    rewritten = _rewrite_line(
                        clients[speaker], speaker, personas[speaker],
                        context, original_text, segment,
                    )
                    line["text"] = rewritten
                except Exception as e:
                    logger.warning(f"Rewrite failed for {speaker}: {e}")

            context_lines.append({"speaker": speaker, "text": line["text"]})

    return script


def _generate_youtube_title(script: dict, topics: list[dict]) -> str:
    """Generate a click-worthy YouTube title from the episode content."""
    client = OpenAI(api_key=config.OPENAI_API_KEY)

    episode_title = script.get("title", "")
    main_topics = [t["title"] for t in topics if t.get("category") == "main"][:3]
    topics_str = "; ".join(main_topics) if main_topics else "AI news"

    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        max_tokens=100,
        messages=[
            {
                "role": "system",
                "content": (
                    "You write YouTube video titles for an AI news podcast called "
                    "'The AI Daily' hosted by ChatGPT and Claude.\n\n"
                    "Rules for great YouTube titles:\n"
                    "- MAX 65 characters (hard limit — YouTube truncates longer ones)\n"
                    "- Lead with the most interesting/controversial topic\n"
                    "- Use a pattern like: 'Topic | The AI Daily' or 'Bold Claim — Topic | AI Daily'\n"
                    "- Create curiosity — make people NEED to click\n"
                    "- Avoid generic words like 'interesting', 'amazing', 'incredible'\n"
                    "- Don't use all caps or excessive punctuation\n"
                    "- Include 'AI Daily' for brand recognition\n\n"
                    "Return ONLY the title text, nothing else."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Episode script title: {episode_title}\n"
                    f"Main topics: {topics_str}\n\n"
                    "Write a click-worthy YouTube title."
                ),
            },
        ],
        temperature=0.9,
    )

    usage = resp.usage
    if usage:
        tracker.record(
            step="youtube_title", model="gpt-4o-mini",
            input_tokens=usage.prompt_tokens,
            output_tokens=usage.completion_tokens,
        )

    yt_title = resp.choices[0].message.content.strip().strip('"')
    logger.info(f"YouTube title: {yt_title}")
    return yt_title


def save_script(script: dict, output_dir: Path) -> Path:
    """Save the script to a JSON file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "script.json"
    path.write_text(json.dumps(script, indent=2, ensure_ascii=False), encoding="utf-8")
    logger.info(f"Script saved to {path}")
    return path
